function MiniComp1 = lireMistrasMiniComp1

%% Import data from text file.
% Script for importing data from the following text file:
%
%    /home/emmanuel.ramasso/Documents/OndesStageFEMPTO/MinicompositeSiC/MC1/MiniComp1.TXT
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2017/07/07 09:06:49

%% Initialize variables.
filename = '/home/emmanuel.ramasso/Documents/OndesStageFEMPTO/MinicompositeSiC/MC1/MiniComp1.TXT';
startRow = 6;

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: double (%f)
%	column12: double (%f)
%   column13: double (%f)
%	column14: double (%f)
%   column15: double (%f)
%	column16: double (%f)
%   column17: double (%f)
%	column18: double (%f)
%   column19: double (%f)
%	column20: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%3f%17f%11f%11f%4f%6f%6f%10f%4f%6f%6f%6f%6f%12f%8f%8f%8f%8f%6f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
textscan(fileID, '%[^\n\r]', startRow-1, 'WhiteSpace', '', 'ReturnOnError', false, 'EndOfLine', '\r\n');
dataArray = textscan(fileID, formatSpec, 'Delimiter', '', 'WhiteSpace', '', 'EmptyValue' ,NaN,'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
MiniComp1 = [dataArray{1:end-1}];
%% Clear temporary variables
clearvars filename startRow formatSpec fileID dataArray ans;